import { TabBarButton, TabBarButtonMobile } from '@/components/TabBar';
import AdminLayout from '@/layout/AdminLayout';
import DashboardLayout from '@/layout/DashboardLayout';
import Head from 'next/head';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardLayout>
        {' '}
        <h1>afasfdsdf</h1>
      </DashboardLayout>
    </div>
  );
}

Home.layout = AdminLayout;
