import Table from '@/components/ListData';
import AdminLayout from '@/layout/AdminLayout';
import DashboardLayout from '@/layout/DashboardLayout';
import Head from 'next/head';
import { useState } from 'react';

export const getServerSideProps = ({ req }) => {
  const user = req.cookies.token;
  console.log('user', user);
  if (!user) {
    return {
      redirect: {
        destination: '/auth/login',
        permanent: false,
      },
    };
  }
  return {
    redirect: {
      destination: '/dashboard',
      permanent: false,
    },
  };

  // return {
  //   props: {},
  // };
};

export default function Home() {
  const [selectedItem, setSelectedItem] = useState('');
  const handleSelect = (id) => {
    return setSelectedItem(id);
  };

  return (
    <div className="">
      <Head>
        <title>UPH MEDAN Booking Lounge Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Table title={selectedItem} />
    </div>
  );
}

Home.layout = AdminLayout;
