import Table from '@/components/Table';
import AdminLayout from '@/layout/AdminLayout';
import DashboardLayout from '@/layout/DashboardLayout';
import Head from 'next/head';
import { useState } from 'react';

export default function Home() {
  const [selectedItem, setSelectedItem] = useState('');
  const handleSelect = (id) => {
    return setSelectedItem(id);
  };

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardLayout selectedItem={selectedItem} handleSelect={handleSelect}>
        <Table title={selectedItem} />
      </DashboardLayout>
    </div>
  );
}

Home.layout = AdminLayout;
